name: 'over.react.experiments'
version: 0.0.1
description: Experiments with Workiva's Over_React package.
#author: Paul Welbourne <paul_welbourne@yahoo.co.uk>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  dart_to_js_script_rewriter: any
  browser_detect: any
  over_react: any
  route_hierarchical: any

transformers:
  - over_react
  # Reminder: dart2js should come after any other transformers that touch Dart code
  - $dart2js
